args:
  latent_channels: 16
  mode: inference
  # load: "{your CogVideoX SAT folder}/transformer" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter
  # load: "/path/to/cogvideox-sat/2b/transformer"
  load: /path/to/FluidNexusRoot/cogvideox_lora_ckpts/lora_cogvidx5b_fluid_nexus_smoke_i2v_fix3samples-10-28-17-06/

  batch_size: 1

  sdedit_strength: 0.5
  sdedit_prompt_idx: 0
  sdedit_labels_dir: /path/to/FluidNexusRoot/FluidNexusSmokeAll_cogvideox_dataset/labels
  sdedit_sequence_name: seq_10_22_01_28_03
  sdedit_frames_dir: /path/to/FluidNexusRoot/FluidNexusSmoke
  sdedit_prefix_start_idx_one: 37
  sdedit_prefix_start_idx_two: 56
  sdedit_prefix_start_idx_three: 56
  sdedit_prefix_num_frames: 9
  sdedit_start_idx_one: 55
  sdedit_label_start_idx_one: 37
  sdedit_start_idx_two: 167
  sdedit_label_start_idx_two: 149
  sdedit_start_idx_three: 279
  sdedit_label_start_idx_three: 261
  sdedit_num_frames: 65
  sdedit_frame_step: 2
  sdedit_zero123_finetune_step: 52000
  sdedit_view_idx: 2
  sdedit_tgt_view_idx: 1
  sdedit_ignore_input_fps: True

  sampling_num_frames: 17  # Must be 13, 11 or 9
  sampling_fps: 8
  # fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B
  output_dir: /path/to/FluidNexusRoot/cogvideox_lora_outputs/5b_lora_all_sdedit_zero123_pi2v_long_fluid_nexus_smoke/
  force_inference: True
